
package com.ositran.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MigraCarnetdeExtrajeriaPortType", targetNamespace = "http://ws.consulta.usuarios.migraciones.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MigraCarnetdeExtrajeriaPortType {


    /**
     * 
     * @param solicitud
     * @return
     *     returns com.ositran.ws.RespuestaBean
     */
    @WebMethod(action = "consultarDocumento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDocumento", targetNamespace = "http://ws.consulta.usuarios.migraciones.gob.pe/", className = "com.ositran.ws.ConsultarDocumento")
    @ResponseWrapper(localName = "consultarDocumentoResponse", targetNamespace = "http://ws.consulta.usuarios.migraciones.gob.pe/", className = "com.ositran.ws.ConsultarDocumentoResponse")
    public RespuestaBean consultarDocumento(
        @WebParam(name = "solicitud", targetNamespace = "")
        SolicitudBean solicitud);

}
