
package com.ositran.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MigraCarnetdeExtrajeria", targetNamespace = "http://ws.consulta.usuarios.migraciones.gob.pe/", wsdlLocation = "https://ws3.pide.gob.pe/services/MigraCarnetdeExtrajeria?wsdl")
public class MigraCarnetdeExtrajeria
    extends Service
{

    private final static URL MIGRACARNETDEEXTRAJERIA_WSDL_LOCATION;
    private final static WebServiceException MIGRACARNETDEEXTRAJERIA_EXCEPTION;
    private final static QName MIGRACARNETDEEXTRAJERIA_QNAME = new QName("http://ws.consulta.usuarios.migraciones.gob.pe/", "MigraCarnetdeExtrajeria");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ws3.pide.gob.pe/services/MigraCarnetdeExtrajeria?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MIGRACARNETDEEXTRAJERIA_WSDL_LOCATION = url;
        MIGRACARNETDEEXTRAJERIA_EXCEPTION = e;
    }

    public MigraCarnetdeExtrajeria() {
        super(__getWsdlLocation(), MIGRACARNETDEEXTRAJERIA_QNAME);
    }

    public MigraCarnetdeExtrajeria(WebServiceFeature... features) {
        super(__getWsdlLocation(), MIGRACARNETDEEXTRAJERIA_QNAME, features);
    }

    public MigraCarnetdeExtrajeria(URL wsdlLocation) {
        super(wsdlLocation, MIGRACARNETDEEXTRAJERIA_QNAME);
    }

    public MigraCarnetdeExtrajeria(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MIGRACARNETDEEXTRAJERIA_QNAME, features);
    }

    public MigraCarnetdeExtrajeria(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MigraCarnetdeExtrajeria(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MigraCarnetdeExtrajeriaPortType
     */
    @WebEndpoint(name = "MigraCarnetdeExtrajeriaHttpsSoap11Endpoint")
    public MigraCarnetdeExtrajeriaPortType getMigraCarnetdeExtrajeriaHttpsSoap11Endpoint() {
        return super.getPort(new QName("http://ws.consulta.usuarios.migraciones.gob.pe/", "MigraCarnetdeExtrajeriaHttpsSoap11Endpoint"), MigraCarnetdeExtrajeriaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MigraCarnetdeExtrajeriaPortType
     */
    @WebEndpoint(name = "MigraCarnetdeExtrajeriaHttpsSoap11Endpoint")
    public MigraCarnetdeExtrajeriaPortType getMigraCarnetdeExtrajeriaHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.consulta.usuarios.migraciones.gob.pe/", "MigraCarnetdeExtrajeriaHttpsSoap11Endpoint"), MigraCarnetdeExtrajeriaPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MIGRACARNETDEEXTRAJERIA_EXCEPTION!= null) {
            throw MIGRACARNETDEEXTRAJERIA_EXCEPTION;
        }
        return MIGRACARNETDEEXTRAJERIA_WSDL_LOCATION;
    }

}
