
package com.ositran.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReniecConsultaDniPortType", targetNamespace = "http://ws.reniec.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReniecConsultaDniPortType {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ositran.ws.ResultadoConsulta
     */
    @WebMethod(action = "consultar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultar", targetNamespace = "http://ws.reniec.gob.pe/", className = "com.ositran.ws.Consultar")
    @ResponseWrapper(localName = "consultarResponse", targetNamespace = "http://ws.reniec.gob.pe/", className = "com.ositran.ws.ConsultarResponse")
    public ResultadoConsulta consultar(
        @WebParam(name = "arg0", targetNamespace = "")
        PeticionConsulta arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ositran.ws.ResultadoActualizacionCredencial
     */
    @WebMethod(action = "actualizarcredencial")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarcredencial", targetNamespace = "http://ws.reniec.gob.pe/", className = "com.ositran.ws.Actualizarcredencial")
    @ResponseWrapper(localName = "actualizarcredencialResponse", targetNamespace = "http://ws.reniec.gob.pe/", className = "com.ositran.ws.ActualizarcredencialResponse")
    public ResultadoActualizacionCredencial actualizarcredencial(
        @WebParam(name = "arg0", targetNamespace = "")
        PeticionActualizarCredencial arg0);

}
