
package com.ositran.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Tramite", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Tramite {


    /**
     * 
     * @param recepcionRequest
     * @return
     *     returns com.ositran.ws.RespuestaTramite
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recepcionarTramiteResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "com.ositran.ws.RecepcionarTramiteResponse")
    @ResponseWrapper(localName = "recepcionarTramiteResponseResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "com.ositran.ws.RecepcionarTramiteResponseResponse")
    @Action(input = "http://ws.wsiotramite.segdi.gob.pe/Tramite/recepcionarTramiteResponseRequest", output = "http://ws.wsiotramite.segdi.gob.pe/Tramite/recepcionarTramiteResponseResponse")
    public RespuestaTramite recepcionarTramiteResponse(
        @WebParam(name = "recepcionRequest", targetNamespace = "")
        RecepcionTramite recepcionRequest);

    /**
     * 
     * @param cargoRequest
     * @return
     *     returns com.ositran.ws.RespuestaCargoTramite
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cargoResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "com.ositran.ws.CargoResponse")
    @ResponseWrapper(localName = "cargoResponseResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "com.ositran.ws.CargoResponseResponse")
    @Action(input = "http://ws.wsiotramite.segdi.gob.pe/Tramite/cargoResponseRequest", output = "http://ws.wsiotramite.segdi.gob.pe/Tramite/cargoResponseResponse")
    public RespuestaCargoTramite cargoResponse(
        @WebParam(name = "cargoRequest", targetNamespace = "")
        CargoTramite cargoRequest);

    /**
     * 
     * @param request
     * @return
     *     returns com.ositran.ws.RespuestaConsultaTramite
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarTramiteResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "com.ositran.ws.ConsultarTramiteResponse")
    @ResponseWrapper(localName = "consultarTramiteResponseResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "com.ositran.ws.ConsultarTramiteResponseResponse")
    @Action(input = "http://ws.wsiotramite.segdi.gob.pe/Tramite/consultarTramiteResponseRequest", output = "http://ws.wsiotramite.segdi.gob.pe/Tramite/consultarTramiteResponseResponse")
    public RespuestaConsultaTramite consultarTramiteResponse(
        @WebParam(name = "request", targetNamespace = "")
        String request);

}
