oSearchData = {
"bandeja":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",2] ] ,
"documentos":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",3] , ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"ingresados":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",3] , ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"esta":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"opci&oacute;n":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"usuario":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"mesa":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"partes":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"visualiza":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"listado":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"los":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",3] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"antes":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"que":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",6] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"sean":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"digitalizados":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"para":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",6] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"ver":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"detalle":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"cada":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"documento":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",13] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"debe":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",5] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"seleccionarlo":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"&eacute;ste":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"ser&aacute;":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"mostrado":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"parte":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"inferior":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"sistema":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"gestion":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"documentaria":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"osinergmin":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"created":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"with":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"the":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"freeware":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"edition":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"helpndoc":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] , ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"easy":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"chm":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"and":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"documentation":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"editor":  [ ["BandejaDeDocumentosIngresados.html","Bandeja De Documentos Ingresados",1] ] ,
"registro":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"nuevo":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",9] ] ,
"registrar":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",5] ] ,
"hacer":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",3] ] ,
"clic":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",5] ] ,
"bot&oacute;n":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",5] ] ,
"registrados":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"mostrada":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"siguiente":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",7] ] ,
"ventana":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",5] ] ,
"corresponde":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"expediente":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",6] ] ,
"existente":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"explorar":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"buscarlo":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"ello":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"mostrar&aacute;":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",9] ] ,
"tienen":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"como":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",3] ] ,
"criterio":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"b&uacute;squeda":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"n&uacute;mero":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",6] ] ,
"identificaci&oacute;n":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"dni":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"ruc":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"nombre":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",3] ] ,
"raz&oacute;n":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"social":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"del":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",9] ] ,
"cliente":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",9] ] ,
"asunto":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"todos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"estos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"campos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"son":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"obligatorios":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"colocamos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"listar&aacute;":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"aquellos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"expedientes":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"coincidan":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"con":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",3] ] ,
"ingresado":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"misma":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"forma":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"sucede":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"otros":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"una":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"vez":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"ubicado":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"cuesti&oacute;n":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"datos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",3] ] ,
"llenos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"propios":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"debemos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"a&ntilde;adir":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"informaci&oacute;n":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"est&aacute;":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"registrando":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"tiene":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"abiertos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"proceso":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"mensaje":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"azul":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"pantalla":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",4] ] ,
"ingresar":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",3] ] ,
"pertenece":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"por":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"defecto":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"&aacute;rea":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"destino":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"persona":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"destinataria":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"luego":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",3] ] ,
"deben":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"tales":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"tipo":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"fecha":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"folios":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"correspondiente":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"secci&oacute;n":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"seleccionar":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"identidad":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"dicho":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"autom&aacute;ticamente":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"personales":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"correspondientes":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"muestra":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"caso":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"est&eacute;":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"registrado":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"puede":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"ser":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"creado":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"haciendo":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"boton":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"cual":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"terminar":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"confirmaci&oacute;n":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"aceptar":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"hacemos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"regresaremos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"seleccionamos":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"imprimir":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",2] ] ,
"cargo":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"easily":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"create":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"pdf":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"help":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ] ,
"documents":  [ ["RegistrodeNuevoDocumento.html","Registro de Nuevo Documento",1] ]
}