oSearchData = {
"bandeja":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",2] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",2] ] ,
"documentos":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",4] ] ,
"ingresados":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",2] ] ,
"esta":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"opci&oacute;n":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"usuario":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"digitalizador":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"visualiza":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"listado":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"los":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",2] , ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"enviados":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"desde":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"mesa":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"partes":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"para":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",2] , ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"que":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"sean":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"digitalizados":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"rechazados":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"por":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"control":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"calidad":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"ver":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"detalle":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"cada":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"documento":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",4] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"debe":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",2] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"seleccionarlo":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"&eacute;ste":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"ser&aacute;":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"mostrado":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"parte":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"inferior":  [ ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"sistema":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"gestion":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"documentaria":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"osinergmin":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"created":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"with":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"the":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"freeware":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"edition":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"helpndoc":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"easy":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"chm":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"and":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"documentation":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"editor":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] , ["Bandejadedocumentosingresados.html","Bandeja de documentos ingresados",1] ] ,
"adjuntar":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",4] ] ,
"archivo":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",4] ] ,
"hacer":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"clic":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"bot&oacute;n":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",3] ] ,
"detalles":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"del":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"registrado":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"mostrada":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"siguiente":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"ventana":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"seleccionar":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"archivos":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"pulsamos":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"abrir":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"mostrar&aacute;":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"pantalla":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"con":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"cargado":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"luego":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"haber":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"adjuntado":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"pulsar":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"registrar":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"mensajes":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"recibidos":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"aprecia":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"aparece":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"porque":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"fue":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ] ,
"enviado":  [ ["AdjuntarunDocumento.html","Adjuntar un Documento",1] ]
}